version: "3"
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    environment:
      SECRET: "yakutia-super-secret-key-2024"
      ADMIN_EMAIL: "admin@yakutia.ru"
      ADMIN_PASSWORD: "admin123"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173"